### ISSUE TITLE
Harvesting fruit from CROPTOPIA Saplings causes server to crash

### ISSUE THREAD

**Issue by sk0mvitor** [wendall911/ActuallyHarvest#12]
Hi @wendall911 ! 
It's my first time ever reporting a bug from a mod, hope I'm doing this the correct way :)
Harvesting fruit from a Croptopia sapling (either with hand or hoe)  causes server to crash
I attached a crashlog from my server so you can check it out

[crash-2024-10-08_22.23.23-server.txt](https://github.com/user-attachments/files/17299576/crash-2024-10-08_22.23.23-server.txt)

**Comment by wendall911** [comment]
I'll take a look at this soon. Thanks for reporting.

**Comment by wendall911** [comment]
Ok, fixed and uploaded to both CurseForge and Modrinth. I had a line missing from the fabric mod config that was needed. I appreciate the report. Also, attaching the crash report is exactly the right thing to do, much appreciated!

**Comment by sk0mvitor** [comment]
Installed the update and it's working fine now! Thanks :)
