### ISSUE TITLE
1.21.4

### ISSUE THREAD

**Issue by janaron** [wendall911/ActuallyHarvest#15]
This is the only missing mod I need before I can upgrade to 1.21.4. Could you please update it? Would be very much appreciated!
Anyways thanks for making such a great mod, been using it a lot!

**Comment by wendall911** [comment]
@janaron I'll have an update out soon.

**Comment by wendall911** [comment]
This is now released on CurseForge and Modrinth. Thanks for your patience. Been busy with other things the last few weeks.
