### ISSUE TITLE
Add that durability is consumed when using a hoe. please.

### ISSUE THREAD

**Issue by bafb** [wendall911/ActuallyHarvest#16]
the same durability is consumed as would be consumed when plowing the land. (9 blocks).
please.
It would give a use to hoes, since we all know they are useless, it would motivate the player to want to craft, improve and enchant a hoe.
it is too overpowered that nothing is consumed and still gives you XP and also replants.
and if you want you could put an option to disable this feature that I am suggesting in case someone does not like this new function they can simply disable it with a button or a command.
thanks :)
i love your mod, makes my life easier.

**Comment by wendall911** [comment]
Good suggestion, I'll see what I can do.

**Comment by wendall911** [comment]
Actually, this is already implemented. Change damageTool to true in the config.
