### ISSUE TITLE
[Suggestion] Double Tall Crops config

### ISSUE THREAD

**Issue by milkev** [wendall911/ActuallyHarvest#8]
Harvestable plants (such as Corn from Extra Delight) have their bottom piece "harvested" when right clicking the bottom piece. Other plants (such as rice from Farmers Delight) have direct support, but it would be cool to have dynamic support, either from an automatic detection (unsure how that would work) or just by a config list that defines what crops are double tall.

**Comment by wendall911** [comment]
Great idea. I'll do a little investigation and report back.

**Comment by wendall911** [comment]
Ok, I will push a release out for this in a little bit here.

**Comment by wendall911** [comment]
Auto detecting double tall crops and doing the correct thing.

**Comment by wendall911** [comment]
Released on both CurseForge and Modrinth.

**Comment by milkev** [comment]
i noticed with the corn from extra delight, when you right click the bottom piece it resets the bottom piece to age 0, instead of keeping it and resetting the age of the top block like it does when you right click the top piece. Is that something that can be fixed?

i tried doing "extradelight:corn_bottom[age=3],extradelight:corn_bottom[age=3]" in the config but the top block gets removed and doesnt regrow. doing "extradelight:corn_bottom[age=3],extradelight:corn_bottom[age=2]" is slightly better, the plant continues to grow properly, but the top block is still removed on right click harvesting the bottom block.

**Comment by wendall911** [comment]
Thanks for the feedback. I'm going to see if I can tweak a little bit to get a better result. I may have a better way to detect double tall plants.

**Comment by wendall911** [comment]
Ok, I took a slightly different approach. Now you can't harvest the bottom block. Try removing the config options you've added and test. It will work as expected now.
