### ISSUE TITLE
Crash with EG Particle Interactions and Double Tall Crops

### ISSUE THREAD

**Issue by milkev** [wendall911/ActuallyHarvest#9]
When EG Particle Interactions is installed and you right click a double tall crop, the player gets kicked. This notably does not happen with other right click to harvest mods (such as right click harvest), making this as a sister issue to [EGParticleInteractions Issue #1](https://github.com/Enchanted-Games/block-place-particles/issues/1)

Test with EG Particle Interactions v0.1.1, Farmers Delight 1.2.4, YACL 3.5.0, Actually Harvest 1.1.0.4
[latest.log](https://github.com/user-attachments/files/16829575/latest.log)

**Comment by wendall911** [comment]
Ok, thanks for the report! I will take a look shortly and resolve.

**Comment by wendall911** [comment]
This is a bug with EG Particle mod, assuming vanilla minecraft behavior. I'm not sure if I can work around this. It would also crash with Quark. I will see if I can workaround.

**Comment by wendall911** [comment]
Ok, I see they just fixed this a few minutes ago in the other mod, will need to wait for a release. I'll close this once you can confirm.

**Comment by milkev** [comment]
can confirm the crash has been fixed with the new version of EG Particle Interactions
